"use client";
import * as React from "react";
import { WorkspaceLink } from "@neton/application-front-workspace";
import { apiFetch, apiWrite } from "@neton/application-front-runtime/client";
import { useMutation, usePermission, useQuery, useQueryClient } from "@neton/application-front-runtime/client-context";
import type { PageResponse } from "@neton/application-front-runtime/types";
import { Button, ConfirmDialog, DataTable, Drawer, Field, FilterPanel, Input, PageHeader, Pagination, RowActions, Select, StatusBadge, Textarea, type DataColumn } from "@neton/application-front-kit";

interface Job { id: number; name: string; handlerName: string; handlerParam?: string | null; cronExpression?: string | null; status: number }
interface JobForm { id?: number; name: string; handlerName: string; handlerParam: string; cronExpression: string; status: number }
type Pending = { type: "delete" | "status" | "trigger"; job: Job };
const emptyForm: JobForm = { name: "", handlerName: "", handlerParam: "", cronExpression: "", status: 0 };

export default function JobListPage() {
  const client = useQueryClient();
  const canCreate = usePermission("infra:job:create"); const canUpdate = usePermission("infra:job:update"); const canDelete = usePermission("infra:job:delete"); const canTrigger = usePermission("infra:job:trigger");
  const [page, setPage] = React.useState(1); const [pageSize, setPageSize] = React.useState(20);
  const [draft, setDraft] = React.useState({ name: "", handlerName: "", status: "" }); const [filters, setFilters] = React.useState(draft);
  const [form, setForm] = React.useState<JobForm | null>(null); const [pending, setPending] = React.useState<Pending | null>(null); const [timesFor, setTimesFor] = React.useState<Job | null>(null); const [error, setError] = React.useState<string | null>(null);
  const params = new URLSearchParams({ pageNo: String(page), pageSize: String(pageSize) }); Object.entries(filters).forEach(([key, value]) => value && params.set(key, value));
  const query = useQuery({ queryKey: ["infra-jobs", page, pageSize, filters], queryFn: () => apiFetch<PageResponse<Job>>(`/admin/infra/job/page?${params}`) });
  const nextTimes = useQuery({ queryKey: ["infra-job-next-times", timesFor?.id], queryFn: () => apiFetch<string[]>(`/admin/infra/job/get_next_times/${timesFor!.id}`), enabled: Boolean(timesFor) });
  const save = useMutation({ mutationFn: (value: JobForm) => apiWrite<void>(`/admin/infra/job/${value.id ? "update" : "create"}`, value.id ? "PUT" : "POST", { ...value, handlerParam: value.handlerParam || null, cronExpression: value.cronExpression || null }), onSuccess: async () => { setForm(null); await client.invalidateQueries({ queryKey: ["infra-jobs"] }); }, onError: (cause: Error) => setError(cause.message) });
  const action = useMutation({ mutationFn: ({ type, job }: Pending) => type === "delete" ? apiWrite<void>(`/admin/infra/job/delete/${job.id}`, "DELETE") : type === "trigger" ? apiWrite<void>(`/admin/infra/job/trigger/${job.id}`, "PUT") : apiWrite<void>(`/admin/infra/job/update-status/${job.id}?status=${job.status === 1 ? 0 : 1}`, "PUT"), onSuccess: async () => { setPending(null); await client.invalidateQueries({ queryKey: ["infra-jobs"] }); } });
  const columns: DataColumn<Job>[] = [
    { key: "name", header: "任务名称", cell: (row) => <strong>{row.name}</strong> }, { key: "handler", header: "处理器", cell: (row) => <code className="text-xs">{row.handlerName}</code> }, { key: "cron", header: "Cron", cell: (row) => <code className="text-xs">{row.cronExpression || "-"}</code> }, { key: "status", header: "状态", cell: (row) => <StatusBadge active={row.status === 1}>{row.status === 1 ? "启用" : "停用"}</StatusBadge> },
    { key: "actions", header: "操作", headerClassName: "text-right", className: "text-right", cell: (row) => <RowActions primary={[...(canUpdate ? [{ label: "编辑", onClick: () => setForm({ id: row.id, name: row.name, handlerName: row.handlerName, handlerParam: row.handlerParam ?? "", cronExpression: row.cronExpression ?? "", status: row.status }) }] : []), ...(canTrigger ? [{ label: "立即执行", onClick: () => setPending({ type: "trigger", job: row }) }] : [])]} more={[{ label: "下次执行时间", onClick: () => setTimesFor(row) }, ...(canUpdate ? [{ label: row.status === 1 ? "暂停任务" : "启用任务", onClick: () => setPending({ type: "status", job: row }) }] : []), ...(canDelete ? [{ label: "删除任务", danger: true, onClick: () => setPending({ type: "delete", job: row }) }] : [])]} /> },
  ];
  return <div className="space-y-4"><PageHeader eyebrow="SCHEDULER" title="定时任务" description="维护调度配置，并执行启停、立即触发和下次运行时间检查。" actions={<>{canCreate && <Button onClick={() => { setError(null); setForm({ ...emptyForm }); }}>新增任务</Button>}<WorkspaceLink to="/infra/job-log" className="inline-flex h-10 items-center rounded-lg border border-[var(--border)] bg-[var(--card)] px-4 text-sm font-semibold hover:bg-[var(--muted)]">任务日志</WorkspaceLink><Button variant="outline" onClick={() => query.refetch()}>刷新</Button></>} />
    <FilterPanel onSubmit={(event) => { event.preventDefault(); setPage(1); setFilters({ name: draft.name.trim(), handlerName: draft.handlerName.trim(), status: draft.status }); }}><div className="admin-filter-grid"><Field label="任务名称"><Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="处理器"><Input value={draft.handlerName} onChange={(event) => setDraft({ ...draft, handlerName: event.target.value })} /></Field><Field label="状态"><Select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option value="">全部</option><option value="1">启用</option><option value="0">停用</option></Select></Field><div className="flex items-end gap-2"><Button type="button" variant="ghost" onClick={() => { const value = { name: "", handlerName: "", status: "" }; setDraft(value); setFilters(value); }}>重置</Button><Button type="submit">查询</Button></div></div></FilterPanel>
    <section className="front-surface overflow-hidden rounded-xl"><DataTable columns={columns} rows={query.data?.list ?? []} rowKey={(row) => row.id} loading={query.isPending} error={query.error?.message} /><Pagination page={page} pageSize={pageSize} total={query.data?.total ?? 0} loading={query.isFetching} onPageChange={setPage} onPageSizeChange={(value) => { setPageSize(value); setPage(1); }} /></section>
    <Drawer open={Boolean(form)} onClose={() => setForm(null)} title={form?.id ? "编辑任务" : "新增任务"} footer={<><Button variant="ghost" onClick={() => setForm(null)}>取消</Button><Button type="submit" form="job-form" disabled={save.isPending}>保存任务</Button></>}>{form && <form id="job-form" className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!form.name.trim() || !form.handlerName.trim()) { setError("请填写任务名称和处理器"); return; } save.mutate({ ...form, name: form.name.trim(), handlerName: form.handlerName.trim() }); }}>{error && <div className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</div>}<Field label="任务名称"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="处理器名称"><Input value={form.handlerName} onChange={(event) => setForm({ ...form, handlerName: event.target.value })} /></Field><Field label="Cron 表达式"><Input value={form.cronExpression} onChange={(event) => setForm({ ...form, cronExpression: event.target.value })} placeholder="例如 0 */5 * * * ?" /></Field><Field label="处理参数"><Textarea value={form.handlerParam} onChange={(event) => setForm({ ...form, handlerParam: event.target.value })} /></Field><Field label="状态"><Select value={form.status} onChange={(event) => setForm({ ...form, status: Number(event.target.value) })}><option value="1">启用</option><option value="0">停用</option></Select></Field></form>}</Drawer>
    <Drawer open={Boolean(timesFor)} onClose={() => setTimesFor(null)} title="下次执行时间" description={timesFor?.name}>{nextTimes.isPending ? <p className="text-sm text-[var(--muted-foreground)]">计算中…</p> : <ol className="space-y-2">{(nextTimes.data ?? []).map((time, index) => <li key={`${time}-${index}`} className="rounded-xl border border-[var(--border)] p-3 text-sm"><span className="mr-3 text-xs font-bold text-[var(--primary)]">{String(index + 1).padStart(2, "0")}</span>{time}</li>)}</ol>}</Drawer>
    <ConfirmDialog open={Boolean(pending)} title={pending?.type === "delete" ? "删除任务" : pending?.type === "trigger" ? "立即执行任务" : pending?.job.status === 1 ? "暂停任务" : "启用任务"} description={pending?.type === "trigger" ? "任务将在后台立即执行一次，执行结果可在任务日志中查看。" : pending?.type === "delete" ? "删除后调度配置不可恢复。" : "状态变更会影响后续调度。"} confirmLabel="确认操作" pending={action.isPending} onCancel={() => setPending(null)} onConfirm={() => pending && action.mutate(pending)} />
  </div>;
}
